#!/usr/bin/env python3
"""Generate games.js from java/jar/*.jar for the static J2meJS launcher."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
JAR_DIR = ROOT / "jar"
OUT = ROOT / "games.js"

JAR_DIR.mkdir(exist_ok=True)

def title_from_name(name: str) -> str:
    stem = Path(name).stem.replace("_", " ").replace("-", " ").strip()
    return " ".join(part.capitalize() if part.islower() else part for part in stem.split()) or name

games = []
for jar in sorted(JAR_DIR.glob("*.jar"), key=lambda p: p.name.lower()):
    games.append({
        "name": title_from_name(jar.name),
        "jar": f"jar/{jar.name}",
    })

content = "// Auto-generated by tools/generate-games-list.py\n"
content += "// Edit manually if your production server stores JARs elsewhere.\n"
content += "window.J2ME_GAMES = " + json.dumps(games, ensure_ascii=False, indent=2) + ";\n"
OUT.write_text(content, encoding="utf-8")
print(f"Generated {OUT.relative_to(ROOT)} with {len(games)} game(s).")
